package annotation.model;
// Generated 2017-7-19 16:18:37 by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * Disease generated by hbm2java
 */
public class Disease implements java.io.Serializable {

	private Integer id;
	private String disease;
	private String username;
	private Date time;

	public Disease() {
	}

	public Disease(String disease, String username, Date time) {
		this.disease = disease;
		this.username = username;
		this.time = time;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDisease() {
		return this.disease;
	}

	public void setDisease(String disease) {
		this.disease = disease;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

}
