package annotation.model;
// Generated 2017-8-2 14:57:29 by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * Entity generated by hbm2java
 */
public class Entity implements java.io.Serializable {

	private Integer id;
	private String pos;
	private String content;
	private String tag;
	private Integer number;
	private String username;
	private String operation;
	private Date time;

	public Entity() {
	}

	public Entity(String pos, String content, String tag, Integer number, String username, String operation,
			Date time) {
		this.pos = pos;
		this.content = content;
		this.tag = tag;
		this.number = number;
		this.username = username;
		this.operation = operation;
		this.time = time;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getPos() {
		return this.pos;
	}

	public void setPos(String pos) {
		this.pos = pos;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getTag() {
		return this.tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

	public Integer getNumber() {
		return this.number;
	}

	public void setNumber(Integer number) {
		this.number = number;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getOperation() {
		return this.operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

}
