package annotation.model;
// Generated 2017-8-2 14:57:29 by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * EntityLabel generated by hbm2java
 */
public class EntityLabel implements java.io.Serializable {

	private Integer id;
	private String tag;
	private String color;
	private String content;
	private String username;
	private Date time;

	public EntityLabel() {
	}

	public EntityLabel(String tag, String color, String content, String username, Date time) {
		this.tag = tag;
		this.color = color;
		this.content = content;
		this.username = username;
		this.time = time;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTag() {
		return this.tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

}
