package annotation.model;
// Generated 2017-8-2 14:57:29 by Hibernate Tools 3.5.0.Final

/**
 * MedicalHistory generated by hbm2java
 */
public class MedicalHistory implements java.io.Serializable {

	private Integer id;
	private String jbxxDengjihao;
	private Integer jbxxNianling;
	private String jbxxXingbie;
	private String dzblZhusu;
	private String dzblXianbingshi;
	private String dzblJiwangbingshi;
	private String dzblChuanranbingshi;
	private String dzblYichuanbingshi;
	private String dzblShiyan;
	private String dzblShijiu;
	private String dzblGuominshi;
	private String dzblWaishangshi;
	private String dzblShoushushi;
	private String jszdRuyuanzhenduanmenzhenzeweimenzhenzhenduan;
	private String jszdChuyuanzhenduansuoyou;
	private String jcCaisechaoshengkeJcjlHqsyz;
	private String jcCaisechaoshengkeJcsjHqsyz;
	private String jcChuangpangJcjlHqsyz;
	private String jcChuangpangJcsjHqsyz;
	private String editXianbingshi;
	private String status;

	public MedicalHistory() {
	}

	public MedicalHistory(String jbxxDengjihao, Integer jbxxNianling, String jbxxXingbie, String dzblZhusu,
			String dzblXianbingshi, String dzblJiwangbingshi, String dzblChuanranbingshi, String dzblYichuanbingshi,
			String dzblShiyan, String dzblShijiu, String dzblGuominshi, String dzblWaishangshi, String dzblShoushushi,
			String jszdRuyuanzhenduanmenzhenzeweimenzhenzhenduan, String jszdChuyuanzhenduansuoyou,
			String jcCaisechaoshengkeJcjlHqsyz, String jcCaisechaoshengkeJcsjHqsyz, String jcChuangpangJcjlHqsyz,
			String jcChuangpangJcsjHqsyz, String editXianbingshi, String status) {
		this.jbxxDengjihao = jbxxDengjihao;
		this.jbxxNianling = jbxxNianling;
		this.jbxxXingbie = jbxxXingbie;
		this.dzblZhusu = dzblZhusu;
		this.dzblXianbingshi = dzblXianbingshi;
		this.dzblJiwangbingshi = dzblJiwangbingshi;
		this.dzblChuanranbingshi = dzblChuanranbingshi;
		this.dzblYichuanbingshi = dzblYichuanbingshi;
		this.dzblShiyan = dzblShiyan;
		this.dzblShijiu = dzblShijiu;
		this.dzblGuominshi = dzblGuominshi;
		this.dzblWaishangshi = dzblWaishangshi;
		this.dzblShoushushi = dzblShoushushi;
		this.jszdRuyuanzhenduanmenzhenzeweimenzhenzhenduan = jszdRuyuanzhenduanmenzhenzeweimenzhenzhenduan;
		this.jszdChuyuanzhenduansuoyou = jszdChuyuanzhenduansuoyou;
		this.jcCaisechaoshengkeJcjlHqsyz = jcCaisechaoshengkeJcjlHqsyz;
		this.jcCaisechaoshengkeJcsjHqsyz = jcCaisechaoshengkeJcsjHqsyz;
		this.jcChuangpangJcjlHqsyz = jcChuangpangJcjlHqsyz;
		this.jcChuangpangJcsjHqsyz = jcChuangpangJcsjHqsyz;
		this.editXianbingshi = editXianbingshi;
		this.status = status;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getJbxxDengjihao() {
		return this.jbxxDengjihao;
	}

	public void setJbxxDengjihao(String jbxxDengjihao) {
		this.jbxxDengjihao = jbxxDengjihao;
	}

	public Integer getJbxxNianling() {
		return this.jbxxNianling;
	}

	public void setJbxxNianling(Integer jbxxNianling) {
		this.jbxxNianling = jbxxNianling;
	}

	public String getJbxxXingbie() {
		return this.jbxxXingbie;
	}

	public void setJbxxXingbie(String jbxxXingbie) {
		this.jbxxXingbie = jbxxXingbie;
	}

	public String getDzblZhusu() {
		return this.dzblZhusu;
	}

	public void setDzblZhusu(String dzblZhusu) {
		this.dzblZhusu = dzblZhusu;
	}

	public String getDzblXianbingshi() {
		return this.dzblXianbingshi;
	}

	public void setDzblXianbingshi(String dzblXianbingshi) {
		this.dzblXianbingshi = dzblXianbingshi;
	}

	public String getDzblJiwangbingshi() {
		return this.dzblJiwangbingshi;
	}

	public void setDzblJiwangbingshi(String dzblJiwangbingshi) {
		this.dzblJiwangbingshi = dzblJiwangbingshi;
	}

	public String getDzblChuanranbingshi() {
		return this.dzblChuanranbingshi;
	}

	public void setDzblChuanranbingshi(String dzblChuanranbingshi) {
		this.dzblChuanranbingshi = dzblChuanranbingshi;
	}

	public String getDzblYichuanbingshi() {
		return this.dzblYichuanbingshi;
	}

	public void setDzblYichuanbingshi(String dzblYichuanbingshi) {
		this.dzblYichuanbingshi = dzblYichuanbingshi;
	}

	public String getDzblShiyan() {
		return this.dzblShiyan;
	}

	public void setDzblShiyan(String dzblShiyan) {
		this.dzblShiyan = dzblShiyan;
	}

	public String getDzblShijiu() {
		return this.dzblShijiu;
	}

	public void setDzblShijiu(String dzblShijiu) {
		this.dzblShijiu = dzblShijiu;
	}

	public String getDzblGuominshi() {
		return this.dzblGuominshi;
	}

	public void setDzblGuominshi(String dzblGuominshi) {
		this.dzblGuominshi = dzblGuominshi;
	}

	public String getDzblWaishangshi() {
		return this.dzblWaishangshi;
	}

	public void setDzblWaishangshi(String dzblWaishangshi) {
		this.dzblWaishangshi = dzblWaishangshi;
	}

	public String getDzblShoushushi() {
		return this.dzblShoushushi;
	}

	public void setDzblShoushushi(String dzblShoushushi) {
		this.dzblShoushushi = dzblShoushushi;
	}

	public String getJszdRuyuanzhenduanmenzhenzeweimenzhenzhenduan() {
		return this.jszdRuyuanzhenduanmenzhenzeweimenzhenzhenduan;
	}

	public void setJszdRuyuanzhenduanmenzhenzeweimenzhenzhenduan(String jszdRuyuanzhenduanmenzhenzeweimenzhenzhenduan) {
		this.jszdRuyuanzhenduanmenzhenzeweimenzhenzhenduan = jszdRuyuanzhenduanmenzhenzeweimenzhenzhenduan;
	}

	public String getJszdChuyuanzhenduansuoyou() {
		return this.jszdChuyuanzhenduansuoyou;
	}

	public void setJszdChuyuanzhenduansuoyou(String jszdChuyuanzhenduansuoyou) {
		this.jszdChuyuanzhenduansuoyou = jszdChuyuanzhenduansuoyou;
	}

	public String getJcCaisechaoshengkeJcjlHqsyz() {
		return this.jcCaisechaoshengkeJcjlHqsyz;
	}

	public void setJcCaisechaoshengkeJcjlHqsyz(String jcCaisechaoshengkeJcjlHqsyz) {
		this.jcCaisechaoshengkeJcjlHqsyz = jcCaisechaoshengkeJcjlHqsyz;
	}

	public String getJcCaisechaoshengkeJcsjHqsyz() {
		return this.jcCaisechaoshengkeJcsjHqsyz;
	}

	public void setJcCaisechaoshengkeJcsjHqsyz(String jcCaisechaoshengkeJcsjHqsyz) {
		this.jcCaisechaoshengkeJcsjHqsyz = jcCaisechaoshengkeJcsjHqsyz;
	}

	public String getJcChuangpangJcjlHqsyz() {
		return this.jcChuangpangJcjlHqsyz;
	}

	public void setJcChuangpangJcjlHqsyz(String jcChuangpangJcjlHqsyz) {
		this.jcChuangpangJcjlHqsyz = jcChuangpangJcjlHqsyz;
	}

	public String getJcChuangpangJcsjHqsyz() {
		return this.jcChuangpangJcsjHqsyz;
	}

	public void setJcChuangpangJcsjHqsyz(String jcChuangpangJcsjHqsyz) {
		this.jcChuangpangJcsjHqsyz = jcChuangpangJcsjHqsyz;
	}

	public String getEditXianbingshi() {
		return this.editXianbingshi;
	}

	public void setEditXianbingshi(String editXianbingshi) {
		this.editXianbingshi = editXianbingshi;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
