package annotation.model;
// Generated 2017-8-2 14:57:29 by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * OtherFeatures generated by hbm2java
 */
public class OtherFeatures implements java.io.Serializable {

	private Integer id;
	private String dengjihao;
	private Integer nianling;
	private String xingbie;
	private String jixing;
	private String xiongtongchengdu;
	private String bingshi;
	private String ucg;
	private String lvef;
	private String diseasename;
	private Date time;

	public OtherFeatures() {
	}

	public OtherFeatures(String dengjihao, Integer nianling, String xingbie, String jixing, String xiongtongchengdu,
			String bingshi, String ucg, String lvef, String diseasename, Date time) {
		this.dengjihao = dengjihao;
		this.nianling = nianling;
		this.xingbie = xingbie;
		this.jixing = jixing;
		this.xiongtongchengdu = xiongtongchengdu;
		this.bingshi = bingshi;
		this.ucg = ucg;
		this.lvef = lvef;
		this.diseasename = diseasename;
		this.time = time;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDengjihao() {
		return this.dengjihao;
	}

	public void setDengjihao(String dengjihao) {
		this.dengjihao = dengjihao;
	}

	public Integer getNianling() {
		return this.nianling;
	}

	public void setNianling(Integer nianling) {
		this.nianling = nianling;
	}

	public String getXingbie() {
		return this.xingbie;
	}

	public void setXingbie(String xingbie) {
		this.xingbie = xingbie;
	}

	public String getJixing() {
		return this.jixing;
	}

	public void setJixing(String jixing) {
		this.jixing = jixing;
	}

	public String getXiongtongchengdu() {
		return this.xiongtongchengdu;
	}

	public void setXiongtongchengdu(String xiongtongchengdu) {
		this.xiongtongchengdu = xiongtongchengdu;
	}

	public String getBingshi() {
		return this.bingshi;
	}

	public void setBingshi(String bingshi) {
		this.bingshi = bingshi;
	}

	public String getUcg() {
		return this.ucg;
	}

	public void setUcg(String ucg) {
		this.ucg = ucg;
	}

	public String getLvef() {
		return this.lvef;
	}

	public void setLvef(String lvef) {
		this.lvef = lvef;
	}

	public String getDiseasename() {
		return this.diseasename;
	}

	public void setDiseasename(String diseasename) {
		this.diseasename = diseasename;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

}
