package annotation.model;
// Generated 2017-8-2 14:57:29 by Hibernate Tools 3.5.0.Final

/**
 * RelationLabel generated by hbm2java
 */
public class RelationLabel implements java.io.Serializable {

	private Integer id;
	private String label;
	private String username;

	public RelationLabel() {
	}

	public RelationLabel(String label, String username) {
		this.label = label;
		this.username = username;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

}
